import { MenuItem, Category, Restaurant } from "./types";

export const mockRestaurant: Restaurant = {
  id: "1",
  name: "Taste Haven",
  logo: "🍽️",
  tagline: "Sabores Autênticos, Ingredientes Frescos",
  whatsappNumber: "5511999999999",
  description: "Experimente excelência culinária com nosso menu selecionado de ingredientes frescos e locais.",
};

export const mockCategories: Category[] = [
  { id: "appetizers", name: "Entradas", icon: "🥗" },
  { id: "mains", name: "Pratos Principais", icon: "🍖" },
  { id: "pasta", name: "Massas", icon: "🍝" },
  { id: "desserts", name: "Sobremesas", icon: "🍰" },
  { id: "beverages", name: "Bebidas", icon: "🥤" },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: "1",
    name: "Lula à Milanesa",
    description: "Lula frita crocante com molho de limão e ervas frescas",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd82b58?w=400&h=300&fit=crop",
    category: "appetizers",
    available: true,
  },
  {
    id: "2",
    name: "Salada do Jardim",
    description: "Mix de folhas com molho da casa, tomate cereja e pepino",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
    category: "appetizers",
    available: true,
  },
  {
    id: "3",
    name: "Salmão Grelhado",
    description: "Salmão fresco do Atlântico com legumes da estação e manteiga de alho",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    category: "mains",
    available: true,
  },
  {
    id: "4",
    name: "Frango Assado com Ervas",
    description: "Peito de frango macio com alecrim, tomilho e batata ao forno",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop",
    category: "mains",
    available: true,
  },
  {
    id: "5",
    name: "Bife Ancho Prime",
    description: "Corte USDA Prime 16oz com purê de batata trufada e verduras da estação",
    price: 32.99,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    category: "mains",
    available: true,
  },
  {
    id: "6",
    name: "Spaguete à Carbonara",
    description: "Clássico italiano com guanciale, pecorino e pimenta do reino",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1612874742237-6526221fcf4f?w=400&h=300&fit=crop",
    category: "pasta",
    available: true,
  },
  {
    id: "7",
    name: "Fettuccine Alfredo",
    description: "Molho cremoso de parmesão com fettuccine fresca e alho",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1645112411341-6c4ee32510d8?w=400&h=300&fit=crop",
    category: "pasta",
    available: true,
  },
  {
    id: "8",
    name: "Penne al Arrabbiata",
    description: "Molho de tomate apimentado com manjericão fresco e parmesão envelhecido",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop",
    category: "pasta",
    available: true,
  },
  {
    id: "9",
    name: "Tiramisu",
    description: "Clássico italiano com mascarpone, espresso e cacau",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1571115764595-644a12c7cb89?w=400&h=300&fit=crop",
    category: "desserts",
    available: true,
  },
  {
    id: "10",
    name: "Bolo de Chocolate Quente",
    description: "Bolo de chocolate morno com o coração derretendo, servido com sorvete de baunilha",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop",
    category: "desserts",
    available: true,
  },
  {
    id: "11",
    name: "Espresso",
    description: "Café italiano rico e encorpado",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b3f2?w=400&h=300&fit=crop",
    category: "beverages",
    available: true,
  },
  {
    id: "12",
    name: "Limonada Fresca",
    description: "Suco de limão recém-espremido com hortelã e gelo",
    price: 4.99,
    image: "https://images.unsplash.com/photo-1585518419759-1410e04c17d3?w=400&h=300&fit=crop",
    category: "beverages",
    available: true,
  },
];
